<a href="https://colab.research.google.com/github/Rohith-2003/Customer-Interest-Analysis/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
thistuple=("aman", "222", 777, 400.4)

In [2]:
d={'rollno': 155, 'Last Name': 'S','First Name': 'Rohith', 'DAteofbirth': '22/05/2003'}

In [16]:
import random as rd

for i in range ( 5 ):
  random.seed (4)
  print (random.randint ( 1 , 1000 )) 

242
242
242
242
242


In [21]:
print(rd.uniform(0.0,1.0))
print(abs(-1234))

0.4788783949238976
1234


In [22]:
rd.randrange(19,91)

30

In [26]:
l=[11,12,13,14,15]
print(rd.sample(l, 3))
rd.shuffle(l);print(l)
print(rd.sample(l,1))
   

[13, 15, 14]
[14, 12, 15, 11, 13]
[11]


In [ ]:
import os
os.mknod("file.txt")
file_open = open("file.txt","w")


In [ ]:
t1 = int(input())
while t1>=1:
  a = [11,15,16,23,74]
  for i in a:
    if i<20:
      print('small')
      continue
    elif i<45:
      print('med')
      break
    else:
      print('large')
  t1 = t1-1

In [ ]:
str = 'The King is Dead, Long live the King'
print(str)
print(str[0])
print(str[2:6])
print(str[2:])
str.split()

In [30]:
import numpy as np
list=[1,4,5,8]
a=np.array(list)
print(a[:2])

[1 4]


In [32]:
list=[[1,2,3],[4,5,6]]
x=np.array(list)
print(x)

[[1 2 3]
 [4 5 6]]


In [36]:
print(x[1,:])

[4 5 6]
